name: charts_flutter
version: 0.6.0
description: Material Design charting library for flutter.
author: Charts Team <charts_flutter@google.com>
homepage: https://github.com/google/charts

environment:
  sdk: '>=1.23.0 <3.0.0'

dependencies:
  # Pointing this to a local path allows for pointing to the latest code
  # in Github for open source development.
  #
  # The pub version of charts_flutter will point to the pub version of charts_common.
  # The latest pub version is commented out and shown below as an example.
  # charts_common: 0.6.0
  charts_common:
    git: 
      url: https://github.com/gazialankus/charts
      path: charts_common
      ref: gazi
  collection: ^1.14.5
  flutter_web: any
  flutter_web_ui: any
  intl: ^0.15.2
  logging: any
  meta: ^1.1.1


dev_dependencies:
  mockito:
  flutter_test:
    sdk: flutter
  test: ^1.3.0

dependency_overrides:
  flutter_web:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web
  flutter_web_ui:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_ui
